# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: The Cloud is the Limit
#email: eric@van-wijk.com
description: >- # this means to ignore newlines until "baseurl:"
  My name is Eric van Wijk, and I'm a Cloud Solution Architect at Microsoft.
  I work with Azure, Azure DevOps, PowerShell, Linux, macOS & Windows. I use this blog to share my experiences with those.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://geekzter.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: geekzter
github_username:  geekzter

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
# - scripts/

# Exclude from processing.
exclude:
  - Brewfile
# The following items will not be processed, by default
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
